### ISSUE TITLE
cannot boot when language is set to japanse

### ISSUE THREAD

**Issue by sonoda944** [jahuerta92/the-yakuza-mod#10]
when booted with japanese used as language, following error code occurs and cannot boot.

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at basemod.ModToggleButton.<init>(ModToggleButton.java:42)
	at basemod.ModLabeledToggleButton.<init>(ModLabeledToggleButton.java:29)
	at basemod.ModLabeledToggleButton.<init>(ModLabeledToggleButton.java:23)
	at basemod.BaseModInit.receivePostInitialize(BaseModInit.java:108)
	at basemod.BaseMod.publishPostInitialize(BaseMod.java:2306)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostInitializeHook.Postfix(PostInitializeHook.java:9)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:307)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

when switched to english language before enabling this mod, it boots up fine,
i dont know my translation files broke or anything, please let me know if i need to do something to fix this

**Comment by jahuerta92** [comment]
There were a couple errors:
- one of the files was malformed, an illegal character.
- the character json file needed two titles for the character.
all is good now, tested it.
